plugin: gcp_compute
projects:
  - <gcp_project_id>
filters:
  - labels.gitlab_node_prefix = <environment_prefix>
keyed_groups:
  - key: labels.gitlab_node_type
    separator: ''
  - key: labels.gitlab_node_level
    separator: ''
scopes:
  - https://www.googleapis.com/auth/compute
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Return the public IP address of the box for connection
  # 'networkInterfaces[0].accessConfigs[0].natIP' is the correct value here and should not be replaced
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
