HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
  <head>
    <title>503 -  GitLab Environment Unavailable</title>
    <link rel='icon' href="https://about.gitlab.com/ico/favicon.ico" type="image/x-icon"/>
  </head>
  <body>
    <div>
      <p style="text-align: center; font-family: sans-serif"><img src="https://about.gitlab.com/images/press/logo/svg/gitlab-logo-gray-rgb.svg" alt="" width="485" height="214" /></p>
      <h2 style="text-align: center; font-family: sans-serif">Sorry, this GitLab environment is not available right now</h2>
      <p style="text-align: center; font-family: sans-serif">This is likely due to it being turned off or it may be experiencing an issue</p>
      <p style="text-align: center; font-family: sans-serif">Please contact the GitLab Quality team for further assistance</p>
    </div>
  </body>
</html>
