- name: Maintenance Mode - Set Maintenance Mode to {{ maintenance_mode_state }} for Omnibus environments
  command: |
    gitlab-rails runner "::Gitlab::CurrentSettings.update!(maintenance_mode: {{ maintenance_mode_state | lower }}, maintenance_mode_message: \"{{ maintenance_mode_message }}\")"
  with_inventory_hostnames:
    - "gitlab_rails_primary:gitlab_rails_secondary:{{ site_group_name }}"
  delegate_to: "{{ node }}"
  register: result
  loop_control:
    loop_var: node
  when:
    - (result.rc | default(1)) != 0 # Keep going until the command is successful on any node
    - not cloud_native_hybrid_geo
    - (site_group_name in group_names)
  run_once: true

- name: Maintenance Mode - Set Maintenance mode to {{ maintenance_mode_state }} for Cloud Native Hybrid environments
  block:
    - name: Maintenance Mode - Configure kubeconfig credentials for Geo primary site
      become: false
      delegate_to: localhost
      run_once: true
      import_tasks: kubeconfig.yml

    - name: Maintenance Mode - Set Maintenance Mode for Cloud Native Hybrid environments
      become: false
      delegate_to: localhost
      run_once: true
      ignore_errors: "{{ maintenance_mode_state | lower }}" # noqa ignore-errors
      kubernetes.core.k8s_exec:
        pod: "{{ task_runner_pod }}"
        namespace: "{{ gitlab_charts_release_namespace }}"
        command: |
          gitlab-rails runner "::Gitlab::CurrentSettings.update!(maintenance_mode: {{ maintenance_mode_state | lower }}, maintenance_mode_message: \"{{ maintenance_mode_message }}\")"
  when:
    - cloud_native_hybrid_geo
