{
 "title": "Server Performance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))))  * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "CPU - {{nodename}}"
    },
    {
     "expr": "sum by (pod)(irate(container_cpu_usage_seconds_total{container=~\".*(webservice|sidekiq).*\"}[5m])) / sum by (pod)(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "CPU - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=~\"node|non_omnibus_node\"} - node_memory_MemAvailable_bytes{job=~\"node|non_omnibus_node\"}) * on(instance) group_left(nodename) (node_uname_info{nodename!~\".*elastic.*\", job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Memory Used MB - {{nodename}}"
    },
    {
     "expr": "((100 - ((node_memory_MemAvailable_bytes{job=~\"node|non_omnibus_node\"} * 100) / node_memory_MemTotal_bytes{job=~\"node|non_omnibus_node\"})) > 75) * on(instance) group_left(nodename)(node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Memory Used % - {{nodename}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=~\".*(webservice|workhorse|sidekiq).*\"}) by (pod)",
     "legendFormat": "Memory Used MB - {{pod}}"
    }
   ]
  },
  {
   "title": "Workhorse HTTP Requests p/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(irate(gitlab_workhorse_http_requests_total[1m]))",
     "legendFormat": "Workhorse req/s"
    }
   ]
  },
  {
   "title": "Controller - Action Requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_transaction_duration_seconds_count{controller!=''}[1m])) by (controller, action) > 0",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "NGINX Stats",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(nginx_ingress_controller_nginx_process_connections{state=~\"active|writing|reading|waiting\"})",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "sum by (job)(irate(nginx_ingress_controller_nginx_process_requests_total[5m]))",
     "legendFormat": "Incoming Requests"
    }
   ]
  },
  {
   "title": "HAProxy HTTP Stats",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_responses_total[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total[5m])) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device!~'rootfs', job=~\"node|non_omnibus_node\"} - node_filesystem_free_bytes{device!~'rootfs', job=~\"node|non_omnibus_node\"}) * on(instance) group_left(nodename)(node_uname_info{job=~\"node|non_omnibus_node\"}) != 0",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Usage Times",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_seconds_total{job=~\"node|non_omnibus_node\"}[1m])) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Disk Usage Time - {{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "iops", "label": "IOPS read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_disk_reads_completed_total{job=~\"node|non_omnibus_node\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Disk IOPS Read Rate - {{nodename}}"
    },
    {
     "expr": "(sum by (instance) (rate(node_disk_writes_completed_total{job=~\"node|non_omnibus_node\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Disk IOPS Write Rate - {{nodename}}"
    }
   ]
  },
  {
   "title": "Disk I/O Byte Rates",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_disk_read_bytes_total{job=~\"node|non_omnibus_node\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Disk Read Rate - {{nodename}}"
    },
    {
     "expr": "(sum by (instance) (rate(node_disk_written_bytes_total{job=~\"node|non_omnibus_node\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Disk Write Rate - {{nodename}}"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "(irate(node_context_switches_total{job=~\"node|non_omnibus_node\"}[5m])) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Context Switches - {{nodename}}"
    },
    {
     "expr": "irate(node_intr_total{job=~\"node|non_omnibus_node\"}[5m])  * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Interrupts - {{nodename}}"
    }
   ]
  },
  {
   "title": "Webserver Workers ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puma_running_workers{pid=\"puma_master\"}",
     "legendFormat": "Puma Running Workers - {{pod}}"
    },
    {
     "expr": "puma_killer_terminations_total{pid=\"puma_master\"}",
     "legendFormat": "Puma Killed Workers - {{pod}}"
    }
   ]
  },
  {
   "title": "Webserver Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(puma_active_connections)",
     "legendFormat": "Puma Active Connections - {{pod}}"
    },
    {
     "expr": "sum by (pod)(puma_queued_connections)",
     "legendFormat": "Puma Queued Connections - {{pod}}"
    }
   ]
  },
  {
   "title": "PgBouncer Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"gitlabhq_production\"})",
     "legendFormat": "Client Active Connections"
    },
    {
     "expr": "sum (pgbouncer_pools_server_active_connections{database=~\"gitlabhq_production\"})",
     "legendFormat": "Server Active Connections "
    },
    {
     "expr": "sum (pgbouncer_pools_client_waiting_connections{database=~\"gitlabhq_production\"})",
     "legendFormat": "Client Waiting Connections "
    }
   ]
  },
  {
   "title": "Postgres Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (instance)(pg_stat_activity_count), \"ip\", \"$1\", \"instance\", \"(.*):.*\") * on(ip) group_left(nodename) (label_replace(node_uname_info{job=~\"node|non_omnibus_node\"}, \"ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "Activity Count - {{nodename}}"
    }
   ]
  },
  {
   "title": "SQL Transactions",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_sql_duration_seconds_count[30s]))",
     "legendFormat": "SQL Transactions"
    }
   ]
  },
  {
   "title": "Redis Cache Queries",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_cache_operation_duration_seconds_count[30s])) by (controller, action)",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Workhorse p95",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Workhorse p95 HTTP Req Duration"
    }
   ]
  },
  {
   "title": "Gitaly p95",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket[5m])) by (le))",
     "legendFormat": "Gitaly p95 GRPC"
    }
   ]
  },
  {
   "title": "Ruby GC Cycles",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ruby_gc_duration_seconds_count[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ruby Heap GC Slots",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(ruby_gc_stat_heap_live_slots)",
     "legendFormat": "Ruby Heap Live Slots - {{pod}}"
    },
    {
     "expr": "sum by (pod)(ruby_gc_stat_heap_free_slots)",
     "legendFormat": "Ruby Heap Free Slots - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((100 - ((node_memory_MemAvailable_bytes{job=~\"node|non_omnibus_node\"} * 100) / node_memory_MemTotal_bytes{job=~\"node|non_omnibus_node\"}))) * on(instance) group_left(nodename) (node_uname_info{job=~\"node|non_omnibus_node\"})",
     "legendFormat": "Memory Used % - {{nodename}}"
    }
   ]
  },
  {
   "title": "Gitaly Read Distribution",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (virtual_storage, storage)(rate(gitaly_praefect_read_distribution[1m]))",
     "legendFormat": "{{virtual_storage}} - {{storage}}"
    }
   ]
  },
  {
   "title": "Gitaly Praefect Cache Access",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (virtual_storage, type)(rate(gitaly_praefect_uptodate_storages_cache_access_total[1m]))",
     "legendFormat": "{{virtual_storage}} - {{type}}"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue)(sidekiq_running_jobs)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "GRPCs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(30, sum by (grpc_code, grpc_method,grpc_service, job)(irate(grpc_client_handled_total[5m])) > 0)",
     "legendFormat": "{{job}} - {{grpc_service}} - {{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "NFS Rate Metrics",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method)(irate(node_nfs_requests_total{proto='4'}[5m]))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by (method)(irate(node_nfsd_requests_total{proto='4'}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "NFS Response/Request time Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "s", "label": "Response time" }
   ],
   "targets": [
    {
     "expr": "sum by (operation)(irate(node_mountstats_nfs_operations_request_time_seconds_total[5m])) > 0",
     "legendFormat": "{{operation}} - Request time"
    },
    {
     "expr": "sum by (operation)(irate(node_mountstats_nfs_operations_queue_time_seconds_total[5m])) > 0",
     "legendFormat": "{{operation}} - Queue time"
    }
   ]
  }
 ]
}