plugin: azure.azcollection.azure_rm

include_vm_resource_groups:
- "<environment_prefix>"

exclude_host_filters:
- tags.gitlab_node_prefix is not defined
- tags.gitlab_node_prefix != '<environment_prefix>'

keyed_groups:
- prefix: ''
  separator: ''
  key: tags.gitlab_node_type | default('ungrouped')
- prefix: ''
  separator: ''
  key: tags.gitlab_node_level | default('ungrouped')
