---
- hosts: all:!gitlab_cluster:!ungrouped
  become: true

  roles:
    - common_vars

  tasks:
    - name: Run GitLab Geo Failover
      import_role:
        name: gitlab_geo
        tasks_from: failover
