---
# Setup and gather vars on all hosts
- hosts: all:!gitlab_cluster:!ungrouped
  gather_facts: false
  tasks:
    - name: Gather Facts
      gather_facts:
      when: ansible_fqdn is not defined
      tags: always

- hosts:
    - gitlab_rails_primary
    - gitlab_rails_secondary
  roles:
    - gitlab_rails
  become: true
