---
# Gather facts on all hosts but only if missing
- hosts: all:!gitlab_cluster:!ungrouped
  gather_facts: false
  tasks:
    - name: Gather Facts
      gather_facts:
      when: ansible_fqdn is not defined
      tags: always

- hosts:
    - redis
    - redis_cache_*
    - redis_persistent_*
  roles:
    - redis
  become: true
