- name: Run gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure

- name: Run {{ gitlab_node_role }} role
  include_role:
    name: "{{ gitlab_node_role }}"

- name: Wait for GitLab Rails to be ready
  uri:
    url: 'http://localhost/-/readiness'
    timeout: 60
  register: result
  until: result.status == 200
  retries: 20
  delay: 5
  when:
    - ('gitlab_rails' in group_names)
    - skip_healthcheck is defined
    - not skip_healthcheck
